kubev2v/migration-planner

.gitignore

- Ignores a top-level `/tmp` directory (facilitates many things during local development, e.g. it is used by used with https://github.com/air-verse/air for performing hot reloading)
- Ignores `*.local.*` files to allow having custom config copies that we don't want to commit to VCS

chore: Updates .gitignore

---

deploy/deploy.mk
deploy/podman/compose.yaml

Details:
- Removes the top-level version field because it is obsolete (see https://github.com/compose-spec/compose-spec/blob/main/spec.md#version-top-level-element-obsolete) and clutters the logs
- Moves the volume definition from the makefile into compose.yaml
- Adds host.docker.internal to /etc/hosts to facilitate debugging the DB
Signed-off-by: Jonathan Kilzi <jkilzi@redhat.com>

chore: Updates the planner-db deployment script

---

internal/agent/agent.go
internal/agent/config.go
internal/agent/fileserver.go
internal/agent/rest.go
internal/agent/server.go

Details:
- Adds an internal file server for serving the UI from within the VM/Agent. The directory holding these files is exposed through the www-dir configuration parameter.
- Prefixes the internal /credentials and /status API endpoints with `/api/v1/...` to differentiate them from the  /login endpoint which is used to display the login form
- Adds an additional field to the Credentials payload: `isDataSharingAllowed` for future use as part of that feature.
Signed-off-by: Jonathan Kilzi <jkilzi@redhat.com>

feat!: Implements the agent's internal file server

---

Dockerfile.agent

Use golang 1.21, because that's version used by latest ubi container.

Add planner-agent dockerfile

---

internal/agent/fileserver.go

This PR fix the lint error errcheck when writing the content of the index file into the ResponseWriter is not handled.

agent/fileserver: Fix lint errcheck

---

.dockerignore
.github/workflows/go.yml
.github/workflows/kind.yml
Makefile
data/ignition.template
deploy/k8s/migration-planner.yaml.template
go.mod
go.sum
internal/image/ova.go
test/e2e/README.md
test/e2e/data/vm.xml
test/e2e/e2e_agent_test.go
test/e2e/e2e_suite_test.go
test/e2e/e2e_test.go
test/e2e/e2e_utils_test.go

This PR add end to end testing.
We use github action CI called `end to end`, which is executed in every PR.
Github CI's ubuntu now support KVM, so tests are quite fast.
The process is:
- setup kind and libvirt
- Deploy vCsim, which is used has vcenter
- Deploy registry where we push agent container
- Build container of agent and push it to registry
- Build container of agent-service and deploy it on kind
- run tests
The tests are using ginkgo. There are few helper methods implemented to help manage VM and sources.
The first end to end test flow:
Before each test:
- Create source
- Download OVA image & extract it
- Run libvirt VM using the ISO from OVA
- Wait for VM IP
- Wait for `planner-agent` service to be running
Test flow:
- Send the vCenter credentials to agent
- Wait until the …

Add end to end tests

---

doc/agentvm.md

Fixes: https://issues.redhat.com/browse/ECOPROJECT-2276

Rephrase the documenation of exploring host directories

---

Containerfile.api
cmd/planner-api/main.go
cmd/planner-api/migrate.go
cmd/planner-api/root.go
cmd/planner-api/run.go

This PR splits the main file into commands to have another command _migrate_ along with the _run_ command.
The `main.go` functionality was moved into `run` command and a new command `migrate` is added that is only migrating the db. The `migrate` command is needed to migrate db during unit tests.

planner-api: Split the main into commands

---

data/ignition.template
internal/agent/inventory.go
test/e2e/e2e_test.go

Fixes: https://issues.redhat.com/browse/ECOPROJECT-2316
This PR changes the network of the containers to be host network, because of the mechanis we report the credenetials URL. In order to get the real host IP instead of the container IP.

Use host network for podman containers

---

internal/store/source.go
internal/store/store.go
internal/store/store_suite_test.go
internal/store/store_test.go
internal/store/transaction.go

Transactions are needed because we must leave the db clean if something happens while mutating data. Currently, we have only one resource _source_ but, with the new multi source model, we'll need to mutate two resources _agent_ and _source_ in the same operation. This requires that the op is done in a transaction.
This commit adds transaction support into the store. The code is largly based on the transaction implementation found in other RH service (e.g. uhc-service-account) but is has been made simplier to fit our needs.
The transactions are wrapped into a context and passed to the store when services are asking for _source_ repository (for now, we have only one. Soon to be more). The store checks the context and if it finds a transaction it will use it to create the source repository. …

store: Add transactions

---

cmd/planner-api/run.go

Seems we lost the autogeneration of the config file during latest refactoring. Adding it back.

Generate default config file on run when missing

---

internal/store/store_test.go

Fix bug that crashes the unit test because the transaction tests are dropping the tables.

store/test: Don't drop table after transaction unit tests

---

internal/service/source.go
internal/store/source.go
internal/store/source_test.go
internal/store/store_test.go

Change the returned value for _List_ method to return a list instead of a pointer to list.

store/source: Return source list instead of pointer to list

---

internal/agent/rest.go
test/e2e/e2e_agent_test.go
test/e2e/e2e_test.go

Fixes: https://github.com/kubev2v/migration-planner/issues/11

Return HTTP 422 in case of wrong URL

---

migration-cluster-day2/charts/migration-cluster-day2/README.md

Updates to the correct migration argo manifest url and adds the required mtv policy command.
Fixes ECOPROJECT-2367

Updates the migration argo manifest url and adds required mtv policy command

---

internal/agent/agent.go
internal/agent/config.go
internal/agent/health.go
internal/agent/inventory.go
internal/agent/server.go

The run command has been refractor to make it simpler. The inventory status method does not have a loop anymore and it is called from the agent itself.
The health check state is checked before sending update requests.
The idea is to reorganize the "inventory" and "healthcheck" into a stateless services and let the agent control everything.
This commit does not change the logic of the agent in any way, it just tries to improve organization of the code and the readability.
Signed-of-by: Cosmin Tupangiu <cosmin@redhat.com>

agent/agent: Refactor run command

---

internal/agent/agent.go
internal/agent/inventory.go
internal/agent/inventory_test.go

The source is not stateful anymore. This PR removes the state from source API.

source: Remove status and status_info from api

---

cmd/planner-agent/main.go
data/ignition.template

This PR adds a service to agent image that is retrieving the system-uuid and write it into `/var/home/core/agent_id`. Agent reads this file at start up.

agent: Retrieve system-uuid

---

go.mod
go.sum
internal/api_server/server.go
internal/auth/auth.go
internal/auth/auth_suite_test.go
internal/auth/none_authenticator.go
internal/auth/rhsso_authenticator.go
internal/auth/rhsso_authenticator_test.go
internal/auth/user.go
internal/config/config.go

This PR adds a simple rhsso authentication.
It validates and parses the token and returns a _User_ simple dto. 
Also, it adds a _NoneAuthenticator_ in case we want no authentication.

auth: Add a simple RHSSO authentication

---

internal/service/agent.go
internal/service/agent_test.go

When list endpoint is called, the soft-deleted agents are present in the response but the soft-deleted agents should be present in the response.

service/agent: Fix bug when soft-deleted agents are listed

---

cmd/planner-agent/main.go

This PR fixes a bug when config validation is not logged on stdout.

agent/run: Show log when config validation failed

---

data/ignition.template
internal/agent/agent.go
internal/agent/rest.go
internal/agent/server.go
internal/client/config.go
internal/image/ova.go

In order to provide proper UI link in the Agent login page, we need to pass the UI link to the agent same as we do pass the link for the Agent API.
The URL call is used here: https://github.com/kubev2v/migration-planner-ui/pull/53

Expose agent /url endpoint to get UI URL

---

cmd/planner-agent/main.go
data/ignition.template
internal/agent/agent.go
internal/agent/agent_test.go
internal/agent/client/planner.go
internal/agent/common/common.go
internal/agent/service/health.go
internal/agent/service/health_test.go
internal/api_server/agentserver/server.go
internal/auth/rhsso_authenticator.go
internal/auth/user.go
internal/image/ova.go
internal/service/image.go

Agent authentication uses the same logic as the planner authorization. For simplicity, the jwt inserted in the ova image is the user's token.

agent/auth: Implement agent authentication

---

data/MigrationAssessment.ovf
internal/image/ova.go
internal/service/image.go
test/e2e/e2e_agent_test.go

- Flush after last header
- rename the VM to MigrationAssessment
- Send Content-Type and Content-length headers

Fix OVA generation

---

Makefile
data/ignition.template

Hi,
Here is a fix for the bug we identified: "Race condition in systemd unit start."
This fix also resolves the failure of the "Deploy assisted-migration" step when running the "run e2e test" workflow, which has been occurring for the past two weeks.

Bug-fix : Race condition in systemd units start

---

.github/workflows/go.yml

Pipeline fails because the lint timeout of 2min is too short. 
This MR increases the timeout to 5min.

Fix lint timeout

---

cmd/planner-api/run.go
internal/service/agent.go
internal/service/agent_test.go
internal/service/mappers/outbound.go
internal/service/source.go
internal/store/inventory.go
internal/store/options.go
internal/store/store.go
internal/store/store_test.go
test/e2e/e2e_agent_test.go

This PR add a Seed() method which will seed the database with default inventory, so the user can do some exploration of what he will get in case he will do the assessment. The default inventory can't be removed and is visible for all users.

Add default inventory

---

.github/workflows/kind.yml
Makefile
deploy/k8s/migration-planner.yaml
deploy/k8s/vcsim.yaml
internal/agent/rest.go
test/e2e/e2e_agent_test.go
test/e2e/e2e_test.go

This PR introduces four additional test cases as part of the end-to-end (e2e) tests to validate login behavior under the following scenarios:
1. Valid credentialsI
2. Invalid credentials
3. Empty username or password
4. Invalid URL
To ensure these tests pass, this PR also addresses the following issues:
Previously, the afterEach block did not remove agent records from the database, even though the associated VM was deleted. This caused failures in the beforeEach block due to unexpected matches between newly created agents and old database records. This has now been fixed.
When an error occurred in the testVmwareConnection method, the expected behavior was to return:
Unauthorized (401) for invalid credentials
BadRequest (400) for other errors
However, this logic was broken due to a if …

Improve the end-to-end tests and fix the issue with 'BeforeEach' code block

---

internal/agent/rest.go

This PR add a new `/api/v1/inventory` endpoint to Agent, so the UI can implement the download inventory button.

Add inventory download URL to agent

---

.gitignore
Makefile
ci/build-deploy.sh
ci/pr-check.sh

This is done as part of onboarding the service to AppSRE Step: Continuous Integration (https://service.pages.redhat.com/dev-guidelines/docs/appsre/onboarding/continuous-integration) Add two kinds of scripts for the migration-planner-service and migration-discovery-agent:
* Build and deploy containers from main branch
* Verify container build before merge PR This change require changing the Makefile and allow using quay.io creds when pushing image to registry Related PR for AppSRE: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/130293

ECOPROJECT-2524: Add scripts to be triggered by AppSRE jobs

---

internal/agent/agent.go
internal/agent/cert_provider.go
internal/agent/cert_provider_test.go
internal/agent/server.go
test/e2e/e2e_agent_test.go
test/e2e/e2e_test.go

When agent boots and gets its credential ip, generate a certificate for that ip and use it to setup tls connection for agent's server.
Replaces: #128 

agent: Generate self signed certificate on the fly

---

Makefile

The validation wasn't good, which caused to error when the envs wasn't provided

Fix QUAY Envs validation

---

internal/agent/agent.go

The issue occurs when the service is unreachable. In agent.go, the function initializeCredentialUrl() returns nil:
`credUrl := a.initializeCredentialUrl()`
Later, when composing the string, a nil reference error occurs when calling to credUrl.IP.String():
`a.credUrl = fmt.Sprintf("%s://%s:%d", protocol, credUrl.IP.String(), defaultAgentPort)`
This PR introduce simple solution for the above bug.

bug-fix: agent crash in disconnected environment

---

internal/image/ova.go

While testing the import from URL in VMware I found out, that VMware requires the OVF to be first file in OVA.

In OVA the first file must be OVF

---

internal/cli/get.go

The table's output includes agent_id and the agent's status and cred URLs.

cli/get: Fix table output format and content

---

internal/api_server/agentserver/server.go
internal/service/agent/handler.go
internal/service/agent/handler_test.go
internal/service/agent/wrapper.go

This PR adds a simple wrapper around agent handler to log the request and error from the actual handler.

agent_handler: Add wrapper to log request and response error

---

deploy/k8s/vcsim-service.yaml
deploy/k8s/vcsim.yaml

Hi,
This PR is a fix for the bug introduced in [ECOPROJECT-2575](https://issues.redhat.com/browse/ECOPROJECT-2575).

bug-fix: vcsim pod clbo deploying migration-planner (make target) on real OCP env

---

doc/deployment.md

Hi,
This PR is in response to: [ECOPROJECT-2422](https://issues.redhat.com/browse/ECOPROJECT-2422).

Agent image section in deployment.md no longer needed

---

cmd/planner/main.go
internal/cli/generate.go
internal/image/builder.go

This PR adds a new command `generate` to generate agent images.

image: Add command to generate agent image

---

doc/debugging.md

Hi Everyone,
I’ve created a document called debugging.md as a follow-up to [ECOPROJECT-2656](https://issues.redhat.com/browse/ECOPROJECT-2656).
I'm pretty sure there's plenty of room for new ideas, improvement and changes in the document. So let me know your thoughts!

Create a documenation how to debug the agent

---

internal/auth/auth.go
internal/auth/none_authenticator.go

Previously `authentication disabled` log entry flood the log like this:
```
2025-02-19T11:09:20+01:00	info	auth	auth/none_authenticator.go:17	authentication disabled
2025-02-19T11:09:20+01:00	info	auth	auth/none_authenticator.go:17	authentication disabled
2025-02-19T11:09:20+01:00	info	auth	auth/none_authenticator.go:17	authentication disabled
2025-02-19T11:09:20+01:00	info	auth	auth/none_authenticator.go:17	authentication disabled
2025-02-19T11:09:20+01:00	info	auth	auth/none_authenticator.go:17	authentication disabled
```
This PR remove this log entry, and add the logging of auth mechanism for each server just once in init stage.

Remove authentication disabled flood from log

---

go.mod
go.sum
internal/service/source_test.go
internal/store/agent_test.go
internal/store/model/source.go
internal/store/source_test.go

This PR adds a unique index in the source model to make the name of the source unique in the namespace of the organization.

store/source: Create unique index between name and org_id

---

internal/auth/rhsso_authenticator.go

This commits replaces the DefaultWithCtx which ends the refresh goroutine after the method returns with the default implementation.

rhsso: Use the default method to create keyFunc

---

deploy/k8s/migration-planner.yaml.template
deploy/templates/service-template.yml

We need to use tcpSocket because HTTP middleware requires Auth bearer token for RHSSO for /health call

Use tcpSocket probe for healtcheck

---

data/ignition.template

This PR adds a systemd generator, which copies oci images from the archive to container storage.

ignition: Copy embeded images from archive to container storage

---

pkg/metrics/inventory_collector.go

This PR adds `assisted_migration` prefix for inventory metrics.

metrics: add prefix to inventory metrics

---

Containerfile.agent
Containerfile.api

This change is done in order to support builds in MacOS machines

Add "linux/amd64" declaration in Dockerfile

---

internal/events/writer_stdout.go

Since we don't use event-streamer anymore, this PR disables the logging of events.

event-streamer: Don't write the event on stdout

---

internal/api_server/server.go
internal/chilogger/chilogger.go

api-server is flooded by GET requests when UI is running, create custom logger that don't log GET requests.

Don't log GET request in api-server

---

dashboards/grafana-assisted-migrations.yaml

Fixes the dashboard title to "Assisted Migrations"

grafana: fix dashboard title

---

internal/agent/agent.go
internal/agent/client/planner.go
internal/agent/config/config.go
internal/agent/fileio/reader.go
internal/agent/rest.go
internal/agent/service/collector.go
internal/agent/service/health.go
internal/agent/service/inventory.go
internal/api_server/agentserver/server.go
internal/api_server/imageserver/server.go
internal/api_server/server.go
internal/auth/rhsso_authenticator.go
internal/cli/generate.go
internal/cli/get.go
internal/image/builder.go
internal/service/image.go
internal/service/image/handler.go
test/e2e/e2e_agent_test.go
test/e2e/e2e_utils_test.go

As part of the hackathon, one of the goals was to standardize the error message logs with a unified syntax, starting with 'failed' at the beginning of each error.
@nirarg @ravraham

modify logging error messages syntax - change "error" to "failed"

---

Makefile
deploy/e2e.mk
deploy/templates/pk-secret-template.yml
deploy/templates/service-template.yml
internal/cli/sso.go
test/e2e/e2e_agent_test.go
test/e2e/e2e_utils_test.go

Hi,
This PR updates the migration-planner service, deployed on Kind, to use local authentication (auth: local). As a result, all communication methods with the service now include a JWT token in the request.

Change the E2E to work with authentication

---

Containerfile.agent-debug
Containerfile.api-debug
Makefile
data/ignition.template
deploy/templates/service-template.yml
internal/image/builder.go

This PR add support for remote debugging.
We add two new container files:
- Containerfile.agent-debug
- Containerfile.api-debug
The makefile has support to build the application in debug mode using
the `DEBUG_MODE` env variable.
So in order to build container in debug mode please run:
`DEBUG_MODE=true make push-containers`
Then to debug the code please follow the guide in `doc/debugdeployment.md`
Signed-off-by: Aviel Segev <asegev@redhat.com>
Signed-off-by: borod108 <boris.od@gmail.com>
Signed-off-by: Ondra Machacek <omachace@redhat.com>

Support remote debugging

---

test/e2e/e2e_agent_test.go
test/e2e/e2e_test.go
test/e2e/e2e_utils_test.go

Hi,
To simulate this scenario, The source is created with bad proxy settings which causes the service to be unreachable from the deployed VM. After confirming that we are in a disconnected environment and the status is` "up-to-date"` via the agent's `/status` endpoint, it downloads the inventory and uploads it to the service manually.

E2E - Add test case for disconnected environment

---

internal/api_server/agentserver/server.go
internal/api_server/imageserver/server.go
internal/api_server/server.go
pkg/metrics/middleware.go

To use the same sli levels as the other services in app-interface, the buckets must be redefined to: 300ms, 500ms, and 1s.
To support that, a new custom metric middleware has been added to the metrics package.

metrics: create own router metric middleware to support slo buckets

---

internal/agent/collector/vsphere.go

This PR is a followup task for: https://github.com/kubev2v/migration-planner/pull/335
With this change the inventory shows:
```
"os": {},
"osInfo": {
"Amazon Linux 2 (64-bit)": {
"count": 1,
"supported": true
},
"Amazon Linux 3 (64-bit)": {
"count": 1,
"supported": true
},
...
```
Signed-off-by: Aviel Segev <asegev@redhat.com>

Remove the deprecated os count
