kubev2v/migration-planner

- internal/agent/inventory.go
- internal/agent/server.go
This PR solves problems with Sprintf formats when value is an integer.
> Solving problems with Sprintf formats

- doc/agentservice.md
- doc/agentvm.md
- doc/deployment.md
This PR adds documentation of the:
- Agent VM
- Agent Service
- Deployment of the project to the Openshift
> Add documentation of service and agent

- internal/agent/rest.go
This PR modify the testing of vmware credentials so it follows the code of the forklift project. Also we return proper error return codes in case something is wrong.
> Modify the testing of vmware credentials

- internal/agent/rest.go
> agent/rest: Fix lint error

- doc/agentservice.md
- doc/agentvm.md
- doc/deployment.md
Perform cleanup of some grammatical errors in the build and deploy service pod docs.
Closes out Bug ECOPROJECT
> Cleanup some grammatical errors in build and deploy service pod docs

- Makefile
This commit add two targets for buid: _build-api_ and _build-agent_. Also, it fixes the deploy-on-openshift target.
> Makefile: add build targets and fix deploy on ocp

- Makefile
Fix 2nd issue when running deploy-on-openshift target fails.
Tested locally and issue did not reoccur.
> Makefile: Fix 2nd bug when deploy-on-openshift target fails

- .github/workflows/go.yml
- Makefile
- test/config.yaml
This PR adds a postgres db to test job and migrate the db.
> actions: Add postgres db to test job and migrate the db

- internal/store/source_test.go
- internal/store/store_suite_test.go
This PR adds unit tests for source store.
> store/source: Add unit tests

- migration-cluster-day2/.github/workflows/lint.yaml
- migration-cluster-day2/.github/workflows/release.yml
- migration-cluster-day2/.gitignore
- migration-cluster-day2/LICENSE
- migration-cluster-day2/README.md
- migration-cluster-day2/charts/migration-cluster-day2/.helmignore
- migration-cluster-day2/charts/migration-cluster-day2/Chart.yaml
- migration-cluster-day2/charts/migration-cluster-day2/README.md
- migration-cluster-day2/charts/migration-cluster-day2/templates/NOTES.txt
- migration-cluster-day2/charts/migration-cluster-day2/templates/_helpers.tpl
- migration-cluster-day2/charts/migration-cluster-day2/templates/image-registry.yaml
- migration-cluster-day2/charts/migration-cluster-day2/templates/lvm-storage-operator.yaml
- migration-cluster-day2/charts/migration-cluster-day2/templates/mtv-init.yaml
- migration-cluster-day2/charts/migration-cluster-day2/templates/mtv-operator.yaml
- migration-cluster-day2/charts/migration-cluster-day2/templates/nmstate-operator.yaml
- migration-cluster-day2/charts/migration-cluster-day2/templates/serviceaccount.yaml
- migration-cluster-day2/charts/migration-cluster-day2/templates/vddk.yaml
- migration-cluster-day2/charts/migration-cluster-day2/values.yaml
- migration-cluster-day2/manifest.yaml
- migration-cluster-day2/mtv-init/Containerfile
- migration-cluster-day2/mtv-init/Makefile
- migration-cluster-day2/mtv-init/go.mod
- migration-cluster-day2/mtv-init/index.html
- migration-cluster-day2/mtv-init/main.go
This work contains the ArgoCD application and the mtv-init web-service
to initiate the MTV provider
Signed-off-by: Roy Golan <rgolan@redhat.com>
> Add migration-cluster-day-2

- cmd/planner-agent/main.go
- internal/agent/agent.go
- internal/agent/agent_test.go
- internal/agent/config/config.go
- internal/agent/rest.go
- internal/agent/server.go
- internal/agent/service/collector.go
- internal/agent/service/health.go
- internal/agent/service/health_test.go
- internal/agent/service/inventory.go
- internal/agent/service/inventory_test.go
- internal/agent/service/status.go
- internal/agent/service/status_test.go
This PR moves the services and agent's configuration into their own module to improve readability.
> agent: Refactor service and config

- internal/auth/rhsso_authenticator.go
- internal/auth/rhsso_authenticator_test.go
- internal/auth/user.go
The right claim for the username is `preffered_username`.
> auth: Fix user claim name

- .github/workflows/build-push-images.yml
- Makefile
Hi,
I have implemented a solution for the request above and conducted some tests. It worked well in my quay environment.
If you have any questions regarding the code or need further clarification, feel free to ask, and I’ll be happy to explain.
Thanks,
Aviel Segev
> Bug-fix: Migration Planner quay images should be tagged with source git commit sha

- Makefile
Hi,
Following the request in the following Jira task: 
https://issues.redhat.com/browse/ECOPROJECT-2415
Here is a simple solution
> Adding a label to the image to set an expiration date of 10 days

- cmd/planner-api/run.go
Show git sha in logs at startup.
> planner/run: Add information about build commit sha

- doc/githubworkflows.md
Hi, 
This document was added in response to the [ECOPROJECT-2421](https://issues.redhat.com/browse/ECOPROJECT-2421) task.
> Add planner image build instructions to git repo

- .github/workflows/build-push-images.yml
- Makefile
- doc/dev.md
Hi,
This document was added in response to the [ECOPROJECT-2421](https://issues.redhat.com/browse/ECOPROJECT-2421) task.
> Add instructions: how to build the images manually and push it to quay

- Makefile
- cmd/planner/main.go
- internal/cli/create.go
This PR adds a new command to create sources.
> cli: Add create command

- internal/image/builder.go
- internal/service/image.go
Image builder allows a more flexible way to generate ova images. It does not change how the image is generated, only provides option to parameterize the image generation process.
> image: Add implementation for image builder

- test/e2e/e2e_agent_test.go
- test/e2e/e2e_test.go
- test/e2e/e2e_utils_test.go
Hi,
This PR adds a test case for VM reboot. Please refer to : [ECOPROJECT-2543](https://issues.redhat.com/browse/ECOPROJECT-2543)
> Add test case for vm reboot

- cmd/planner/main.go
- internal/auth/auth.go
- internal/cli/deploy.go
- internal/cli/generate.go
- internal/cli/global.go
- internal/cli/sso.go
- internal/config/config.go
This command generates tokens and private key, which helps working locally with sso enabled.
> cli: add sso command to generate tokens and private key

- deploy/deploy.mk
Bug on podman-compose 1.3.0: https://github.com/containers/podman-compose/issues/1109
> A workaround to fix podman-compose absolute path.

- cmd/planner-api/run.go
- internal/store/model/inventory_stats.go
- internal/store/options.go
- internal/store/store.go
- pkg/metrics/inventory_collector.go
- pkg/metrics/metrics.go
This PR adds metrics for service dashboards.
```
HELP inventory_customers_total Total number of customers. Organization is counted.
inventory_customers_total 2
inventory_inventories_total 2
inventory_vms_by_customer_total{org_id="new_org"} 107
inventory_vms_by_customer_total{org_id="org_1"} 107
inventory_vms_by_os_total{os="Amazon Linux 2 (64-bit)"} 2
inventory_vms_by_os_total{os="CentOS 7 (64-bit)"} 2
inventory_vms_by_os_total{os="CentOS 8 (64-bit)"} 2
inventory_vms_by_os_total{os="Debian GNU/Linux 12 (64-bit)"} 2
inventory_vms_by_os_total{os="FreeBSD (64-bit)"} 4
inventory_vms_by_os_total{os="Microsoft Windows 10 (64-bit)"} 4
inventory_vms_by_os_total{os="Microsoft Windows 11 (64-bit)"} 4
inventory_vms_by_os_total{os="Microsoft Windows Server 2019 (64-bit)"} 16 …
```
> service-dashboards: Add metrics for service dashboards

- CONTRIBUTING.md
Hi,
Please feel free to comment if anything is missing or if any changes are needed.
> Add a contribution guide for our github repository

- internal/auth/rhsso_authenticator.go
Log error when parsing failed.
> auth: log error

- internal/auth/rhsso_authenticator.go
- internal/auth/rhsso_authenticator_test.go
This PR checks if orgID claim is found in the token claims or tries to extract from username if the username has an email format. Otherwise return error
> auth: Extract orgID correctly from claims

- internal/auth/rhsso_authenticator.go
- internal/auth/rhsso_authenticator_test.go
Disable expiration check temporary.
> auth: temporary don't check exp of the token

- internal/store/model/inventory_stats.go
Only sources with inventory are taken into account. 
Fixes: https://issues.redhat.com/browse/ECOPROJECT-2744
> inventory stats: Fix total_inventories metric

- internal/cli/get.go
This PR adds a new column to get sources output to show if the source has inventory or not.
> cli: Add has_inventory column to get sources output

- .github/workflows/kind.yml
- Makefile
Support oc installation on linux in the Makefile
Instead of running it from the workflow
In case of mac OS,  return error if not installed
> Move oc installation to Makefile

- Makefile
- doc/deployment.md
This change is done following the change of using template files
> Change deploy on Openshift instructions

- internal/store/model/inventory_stats.go
- pkg/metrics/inventory_collector.go
This metric counts the total number of assessments (with and without inventories).
> metrics: Add metric for total assessments

- deploy/e2e.mk
- test/e2e/e2e_agent_test.go
- test/e2e/e2e_test.go
- test/e2e/e2e_utils_test.go
Hi,
The test case is about downloading the image by URL using `/api/v1/sources/{id}/image-url` endpoint.
> Add test case for downloading the image by URL

- dashboards/grafana-assisted-migrations.yaml
- dashboards/grafana.json
This PR updates backend metrics (not service dashboards).
> dashboards: update backend metrics

- internal/auth/rhsso_authenticator.go
There are usecases that token contains this:
{'organization': {'id': __id__}}
> Parse also organization from token

- internal/api_server/server.go
- pkg/log/chilogger.go
to have all related loggers under the same package.
> move  chilogger.go from chilogger package to to log package

- doc/local_auth.md
> doc: Add documentation for setting up local auth

- .github/workflows/go.yml
Goose needs to know where the sql files are located. This PR prepares the workflows for goose to work properly.
> workflows: Prepare test and migrate target for goose migrations

- doc/migrations.md
> doc: Add migration documentation

- doc/cli.md
> doc: cli documentation

- deploy/e2e.mk
- test/e2e/e2e_agent_test.go
- test/e2e/e2e_disconnected_env_test.go
- test/e2e/e2e_ova_from_url_test.go
- test/e2e/e2e_test.go
- test/e2e/e2e_utils_test.go
- Fixed persistent storage issue in E2E tests that caused failures.
- Moved two specialized tests (Disconnected environment, Download image from URL) to a dedicated files for simplification and better readability.
- Refactored helper functions by moving assertions to describe variables.
- Replaced global variables by integrating them into describe variables.
- Added logging for tests and disabled port-forwarding messages.
- Consolidated VCenter login tests into a single test to improve runtime efficiency.
> E2E Fix and Improvements – See Description

- internal/auth/rhsso_authenticator.go
> rhsso: verify token expiration
